

describe('OnBoard new User', () => {
     beforeEach(() => {
          cy.visit('http://localhost:3000/')
     })

     const firstNameInput = () => cy.get('[data-cy=firstName]')
     const lastNameInput = () => cy.get('[data-cy=lastName]')
     const emailInput = () => cy.get('[data-cy=email]')
     const passwordInput = () => cy.get('[data-cy=password]')
     const tosBox = () => cy.get('[data-cy=tos]')
     const submitButton = () => cy.get('[data-cy=submit]')

     it('sanity test', () => {
          expect(true).to.equal(true)
     })

     it('verify elements exist', () => {
          firstNameInput().should('exist')
          lastNameInput().should('exist')
          emailInput().should('exist')
          passwordInput().should('exist')
          tosBox().should('exist')
     })

     it('type into first name box', () => {
          firstNameInput()
          .should('have.value', '')
          .type('Trenten')
          .should('have.value', 'Trenten')
     })
     it('type into last name box', () => {
          lastNameInput()
          .should('have.value', '')
          .type('Grede')
          .should('have.value', 'Grede')
     })
     it('type into email box', () => {
          emailInput()
          .should('have.value', '')
          .type('test@test.com')
          .should('have.value', 'test@test.com')
     })
     it('type into password box', () => {
          passwordInput()
          .should('have.value', '')
          .type('passwordTest')
          .should('have.value', 'passwordTest')
     })
     it('check tos box', () => {
          tosBox()
          .should('have.value', 'false')
          .check()
          .should('have.value', 'true')
     })
     it('can submit', () => {
          firstNameInput()
          .type('Trenten')
          lastNameInput()
          .type('Grede')
          emailInput()
          .type('test@test.com')
          passwordInput()
          .type('test1234')
          tosBox()
          .check()
          submitButton()
          submitButton().should('not.be.disabled')
          .click()
     })
     it("wont allow submit if an input isn't filled", () => {
          firstNameInput()
          .type('Trenten')
          lastNameInput()
          .type('Grede')
          emailInput()
          .type('test@test.com')
          passwordInput()
          .type('test1234')
          // tosBox()
          // .check()
          submitButton().should('be.disabled')
          firstNameInput().clear()
          lastNameInput().clear()
          emailInput().clear()
          passwordInput().clear()
          tosBox().uncheck()

          firstNameInput()
          .type('Trenten')
          lastNameInput()
          .type('Grede')
          emailInput()
          .type('test@test.com')
          // passwordInput()
          // .type('test1234')
          tosBox()
          .check()
          submitButton().should('be.disabled')
          firstNameInput().clear()
          lastNameInput().clear()
          emailInput().clear()
          passwordInput().clear()
          tosBox().uncheck()

          firstNameInput()
          .type('Trenten')
          lastNameInput()
          .type('Grede')
          // emailInput()
          // .type('test@test.com')
          passwordInput()
          .type('test1234')
          tosBox()
          .check()
          submitButton().should('be.disabled')
          firstNameInput().clear()
          lastNameInput().clear()
          emailInput().clear()
          passwordInput().clear()
          tosBox().uncheck()

          firstNameInput()
          .type('Trenten')
          // lastNameInput()
          // .type('Grede')
          emailInput()
          .type('test@test.com')
          passwordInput()
          .type('test1234')
          tosBox()
          .check()
          submitButton().should('be.disabled')
          firstNameInput().clear()
          lastNameInput().clear()
          emailInput().clear()
          passwordInput().clear()
          tosBox().uncheck()

          // firstNameInput()
          // .type('Trenten')
          lastNameInput()
          .type('Grede')
          emailInput()
          .type('test@test.com')
          passwordInput()
          .type('test1234')
          tosBox()
          .check()
          submitButton().should('be.disabled')
          firstNameInput().clear()
          lastNameInput().clear()
          emailInput().clear()
          passwordInput().clear()
          tosBox().uncheck()
     })

})